FROM ghcr.io/we-promise/sure:stable

USER root
COPY start.sh /app/code/start.sh
RUN chmod 0755 /app/code/start.sh && mkdir -p /app/data && chown -R cloudron:cloudron /app/data

ENV SELF_HOSTED=true \
    ONBOARDING_STATE=open \
    RAILS_FORCE_SSL=false \
    RAILS_ASSUME_SSL=true \
    PORT=3000

EXPOSE 3000
CMD ["/app/code/start.sh"]
